### ISSUE TITLE
Incorrect parsing of some lists

### ISSUE THREAD

**Issue by lorenzoiuri** [mrbaseman/parse_yaml#16]
I've experienced an incorrect parsing of list items.

This yaml produces the variables below, in particular:
- `api_plan_keyless_resource_filtering_whitelist_1='path: /swagger'` 
whereas I expected 
- `api_plan_keyless_resource_filtering_whitelist_1_path=/swagger`

```yaml
api:
  name: be-dotnet-01
  add_env_prefix: false
  version: v1
  enabled: true
  plan:
    keyless:
      enabled: true
      resource_filtering:
        enable: true
        whitelist:
          - path: "/swagger"
            methods: ["GET", "PUT"]
    jwt:
      enabled: false
    apikey:
      enabled: false
```
```shell
...
api_plan_=' api_plan_keyless api_plan_jwt api_plan_apikey'
api_plan_keyless_=' api_plan_keyless_enabled api_plan_keyless_resource_filtering'
api_plan_keyless_enabled=true
api_plan_keyless_resource_filtering_=' api_plan_keyless_resource_filtering_enable api_plan_keyless_resource_filtering_whitelist'
api_plan_keyless_resource_filtering_enable=true
api_plan_keyless_resource_filtering_whitelist_=' api_plan_keyless_resource_filtering_whitelist_1'
api_plan_keyless_resource_filtering_whitelist_1='path: /swagger'
api_plan_keyless_resource_filtering_whitelist_1_=' api_plan_keyless_resource_filtering_whitelist_1_methods'
api_plan_keyless_resource_filtering_whitelist_1_methods_=' api_plan_keyless_resource_filtering_whitelist_1_methods_1 api_plan_keyless_resource_filtering_whitelist_1_methods_2'
api_plan_keyless_resource_filtering_whitelist_1_methods_1=GET
api_plan_keyless_resource_filtering_whitelist_1_methods_2=DELETE
...
```

The following yaml, instead, seems to be parsed fine:
```yaml
api:
  name: be-dotnet-01
  add_env_prefix: false
  version: v1
  enabled: true
  plan:
    keyless:
      enabled: true
      resource_filtering:
        enable: true
        whitelist:
          -
            path: "/swagger"
            methods: ["GET", "DELETE"]
    jwt:
      enabled: false
    apikey:
      enabled: false
```
```bash
...
api_plan_=' api_plan_keyless api_plan_jwt api_plan_apikey'
api_plan_keyless_=' api_plan_keyless_enabled api_plan_keyless_resource_filtering'
api_plan_keyless_enabled=true
api_plan_keyless_resource_filtering_=' api_plan_keyless_resource_filtering_enable api_plan_keyless_resource_filtering_whitelist'
api_plan_keyless_resource_filtering_enable=true
api_plan_keyless_resource_filtering_whitelist_=' api_plan_keyless_resource_filtering_whitelist_1'
api_plan_keyless_resource_filtering_whitelist_1_=' api_plan_keyless_resource_filtering_whitelist_1_path api_plan_keyless_resource_filtering_whitelist_1_methods'
api_plan_keyless_resource_filtering_whitelist_1_methods_=' api_plan_keyless_resource_filtering_whitelist_1_methods_1 api_plan_keyless_resource_filtering_whitelist_1_methods_2'
api_plan_keyless_resource_filtering_whitelist_1_methods_1=GET
api_plan_keyless_resource_filtering_whitelist_1_methods_2=DELETE
api_plan_keyless_resource_filtering_whitelist_1_path=/swagger
...
```

How I ran the script (in the bash shell):
- `source parse_yaml.sh`
- `eval $(parse_yaml api.yaml)`
- `set -o posix ; set | grep keyless`
