### ISSUE TITLE
Tags with dots are not parsed correctly

### ISSUE THREAD

**Issue by abysas** [mrbaseman/parse_yaml#22]
Parsing the sample:
```yaml
key.withdots: blue
another.key: yellow
key: red
```

results to:
```
="key.withdots: blue"
="key.withdots: blue another.key: yellow"
key="red"
__=" key"
```
