### ISSUE TITLE
Parseing YAML issue

### ISSUE THREAD

**Issue by nctiggy** [mrbaseman/parse_yaml#25]
Hi, Thanks for your wonderful function! I have the following yaml
```
---
tools:
  - name: fly
    version_command: "fly --version"
    minimum_version: "5.6"
  - name: docker
    version_command: "docker --version | awk -F'[, ]' '{print $3}' | awk -F'[-]' '{print $1}'"
    minimum_version: "24.0"
```

When I parse the docker version command the first awk command loses some info. In particular the comma and the following space. Any way to work around this?

```
docker --version | awk -F'[]' '{print $3}' | awk -F'[-]' '{print $1}'
```
